spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: Salesforce@1
  server:
    port: 8082

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://db:3306/book?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Salesforce@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8082
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: Salesforce@1
  server:
    port: 8082
